title: "GIMLA PSI LCA"
author: "Your Name"

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_issues_button: true

repository:
  url: "https://github.com/auribep18/GIMLA-PSI-LCA"
  branch: "main"

sphinx:
  config:
    html_theme: "sphinx_book_theme"
    html_theme_options:
      repository_url: "https://github.com/auribep18/GIMLA-PSI-LCA"
      use_repository_button: true
      use_issues_button: true
